# 🎧 Аудио
audio-file-auto=exact                  # Автоматически подключать внешнюю аудиодорожку с тем же именем
audio-file-paths=Sound Reanimedia;Дубляж;Озвучка
alang=ru,eng,jpn                       # Предпочтение: русская, потом английская, потом японская
volume=80                              # Стартовая громкость
							           
# 🎞 Видео                             
vo=gpu                                 # Видеовывод через GPU
profile=gpu-hq                         # Профиль высокого качества
hwdec=auto                             # Аппаратное ускорение
							           
# 💬 Субтитры                          
sub-auto=fuzzy                         # Искать субтитры по совпадению имени
sub-file-paths=Sub (полные);Sub (только надписи)
slang=ru,eng                           # Показывать русские или английские субтитры
sub-font-size=50                       # Увеличенный шрифт
sub-border-size=3                      # Чёрная обводка для читаемости
							           
# ⚙️ Поведение                         
save-position-on-quit=yes              # Запоминать позицию при выходе
fs=yes                                 # Запуск в полноэкранном режиме
pause=no                               # Не ставить на паузу при запуске
osd-level=1                            # Показывать базовую информацию (громкость, дорожка)



osd-status-msg=${playback-time/full} / ${duration} (${percent-pos}%)\nframe: ${estimated-frame-number} / ${estimated-frame-count}
screenshot-directory="C:\Users\KyrRt1n\Desktop\Buhs\mpv\screenshots"
screenshot-template=mpv_%f_%P
